// flow-typed signature: 320e30a74aab86def6e523eacab471d3
// flow-typed version: <<STUB>>/oc-client-browser_v^1.3.4/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oc-client-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oc-client-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oc-client-browser/dist/oc-client.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oc-client-browser/dist/oc-client.min.js' {
  declare module.exports: $Exports<'oc-client-browser/dist/oc-client.min'>;
}
declare module 'oc-client-browser/index' {
  declare module.exports: $Exports<'oc-client-browser'>;
}
declare module 'oc-client-browser/index.js' {
  declare module.exports: $Exports<'oc-client-browser'>;
}
