// flow-typed signature: ed3cdbea98fe2d8d891cfd31a2a0ea4a
// flow-typed version: <<STUB>>/ot-discovery_v^2.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ot-discovery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ot-discovery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ot-discovery/lib/AnnouncementIndex' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/ConsoleLogger' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/DiscoveryAnnouncer' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/DiscoveryClient' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/DiscoveryNotifier' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/DiscoveryWatcher' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/ServerList' {
  declare module.exports: any;
}

declare module 'ot-discovery/lib/Utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ot-discovery/lib/AnnouncementIndex.js' {
  declare module.exports: $Exports<'ot-discovery/lib/AnnouncementIndex'>;
}
declare module 'ot-discovery/lib/ConsoleLogger.js' {
  declare module.exports: $Exports<'ot-discovery/lib/ConsoleLogger'>;
}
declare module 'ot-discovery/lib/DiscoveryAnnouncer.js' {
  declare module.exports: $Exports<'ot-discovery/lib/DiscoveryAnnouncer'>;
}
declare module 'ot-discovery/lib/DiscoveryClient.js' {
  declare module.exports: $Exports<'ot-discovery/lib/DiscoveryClient'>;
}
declare module 'ot-discovery/lib/DiscoveryNotifier.js' {
  declare module.exports: $Exports<'ot-discovery/lib/DiscoveryNotifier'>;
}
declare module 'ot-discovery/lib/DiscoveryWatcher.js' {
  declare module.exports: $Exports<'ot-discovery/lib/DiscoveryWatcher'>;
}
declare module 'ot-discovery/lib/ServerList.js' {
  declare module.exports: $Exports<'ot-discovery/lib/ServerList'>;
}
declare module 'ot-discovery/lib/Utils.js' {
  declare module.exports: $Exports<'ot-discovery/lib/Utils'>;
}
