// flow-typed signature: 81eac0485aa7b5ff41174d2d5ff80ac7
// flow-typed version: <<STUB>>/stream-template_v0.0.10/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-template/stream-template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-template/stream-template.js' {
  declare module.exports: $Exports<'stream-template/stream-template'>;
}
