// flow-typed signature: bc24885f3836f3a2113afb109a758916
// flow-typed version: <<STUB>>/supervisor_v^0.12.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'supervisor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'supervisor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'supervisor/lib/cli-wrapper' {
  declare module.exports: any;
}

declare module 'supervisor/lib/supervisor' {
  declare module.exports: any;
}

declare module 'supervisor/test/fixture' {
  declare module.exports: any;
}

declare module 'supervisor/test/sampleApp/server' {
  declare module.exports: any;
}

declare module 'supervisor/test/supervisor.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'supervisor/lib/cli-wrapper.js' {
  declare module.exports: $Exports<'supervisor/lib/cli-wrapper'>;
}
declare module 'supervisor/lib/supervisor.js' {
  declare module.exports: $Exports<'supervisor/lib/supervisor'>;
}
declare module 'supervisor/test/fixture.js' {
  declare module.exports: $Exports<'supervisor/test/fixture'>;
}
declare module 'supervisor/test/sampleApp/server.js' {
  declare module.exports: $Exports<'supervisor/test/sampleApp/server'>;
}
declare module 'supervisor/test/supervisor.test.js' {
  declare module.exports: $Exports<'supervisor/test/supervisor.test'>;
}
