// flow-typed signature: a7ac745823856a44200e0adbc923fbaf
// flow-typed version: <<STUB>>/warm-require_v^0.2.5/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'warm-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'warm-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'warm-require/chokidar-config' {
  declare module.exports: any;
}

declare module 'warm-require/errors' {
  declare module.exports: any;
}

declare module 'warm-require/module-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'warm-require/chokidar-config.js' {
  declare module.exports: $Exports<'warm-require/chokidar-config'>;
}
declare module 'warm-require/errors.js' {
  declare module.exports: $Exports<'warm-require/errors'>;
}
declare module 'warm-require/index' {
  declare module.exports: $Exports<'warm-require'>;
}
declare module 'warm-require/index.js' {
  declare module.exports: $Exports<'warm-require'>;
}
declare module 'warm-require/module-loader.js' {
  declare module.exports: $Exports<'warm-require/module-loader'>;
}
