// flow-typed signature: b0c2bb3c1c16322efed47524890d05e2
// flow-typed version: <<STUB>>/webpack-register_v^0.2.6/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-register'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-register' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-register/lib/build' {
  declare module.exports: any;
}

declare module 'webpack-register/lib/buildContentMap' {
  declare module.exports: any;
}

declare module 'webpack-register/lib/emptyOutputFileSystem' {
  declare module.exports: any;
}

declare module 'webpack-register/lib/hook' {
  declare module.exports: any;
}

declare module 'webpack-register/lib/normalizeExt' {
  declare module.exports: any;
}

declare module 'webpack-register/lib/normalizeFilename' {
  declare module.exports: any;
}

declare module 'webpack-register/lib/singletonOpt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-register/index' {
  declare module.exports: $Exports<'webpack-register'>;
}
declare module 'webpack-register/index.js' {
  declare module.exports: $Exports<'webpack-register'>;
}
declare module 'webpack-register/lib/build.js' {
  declare module.exports: $Exports<'webpack-register/lib/build'>;
}
declare module 'webpack-register/lib/buildContentMap.js' {
  declare module.exports: $Exports<'webpack-register/lib/buildContentMap'>;
}
declare module 'webpack-register/lib/emptyOutputFileSystem.js' {
  declare module.exports: $Exports<'webpack-register/lib/emptyOutputFileSystem'>;
}
declare module 'webpack-register/lib/hook.js' {
  declare module.exports: $Exports<'webpack-register/lib/hook'>;
}
declare module 'webpack-register/lib/normalizeExt.js' {
  declare module.exports: $Exports<'webpack-register/lib/normalizeExt'>;
}
declare module 'webpack-register/lib/normalizeFilename.js' {
  declare module.exports: $Exports<'webpack-register/lib/normalizeFilename'>;
}
declare module 'webpack-register/lib/singletonOpt.js' {
  declare module.exports: $Exports<'webpack-register/lib/singletonOpt'>;
}
